
services:

#################################################################
# Nessie Postgresql
#################################################################
  nessie-db:
    image: postgres:latest
    container_name: nessie-db
    environment:
      POSTGRES_DB: ${NESSIE_DB_NAME}
      POSTGRES_USER: ${NESSIE_DB_USER}
      POSTGRES_PASSWORD: ${NESSIE_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${NESSIE_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - /opt/nessie/data:/var/lib/postgresql/data
    networks:
      - datalakehouse-network

#################################################################
# Nessie
#################################################################
  nessie:
    image: projectnessie/nessie
    container_name: nessie
    ports:
      - "19120:19120"
    environment:
      NESSIE_VERSION_STORE_TYPE: JDBC
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://nessie-db:5432/${NESSIE_DB_NAME}
      QUARKUS_DATASOURCE_USERNAME: ${NESSIE_DB_USER}
      QUARKUS_DATASOURCE_PASSWORD: ${NESSIE_DB_PASSWORD}
      # nessie.version.store.type: IN_MEMORY
      nessie.catalog.default-warehouse: warehouse
      nessie.catalog.warehouses.warehouse.location: s3a://warehouse/
      nessie.catalog.service.s3.default-options.endpoint: ${MINIO_HOST}:${MINIO_PORT}
      nessie.catalog.service.s3.default-options.path-style-access: true
      nessie.catalog.service.s3.default-options.access-key: urn:nessie-secret:quarkus:nessie.catalog.secrets.access-key
      nessie.catalog.secrets.access-key.name: ${MINIO_ROOT_USER}
      nessie.catalog.secrets.access-key.secret: ${MINIO_ROOT_PASSWORD}
      nessie.catalog.service.s3.default-options.region: us-east-1
      nessie.server.authentication.enabled: false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19120/api/v1/config"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      nessie-db:
        condition: service_healthy
    networks:
      - datalakehouse-network

#################################################################
# iceberg-rest
#################################################################
  rest:
    image: apache/iceberg-rest-fixture
    container_name: iceberg-rest
    ports:
      - 8181:8181
    environment:
      AWS_ACCESS_KEY_ID: ${ICEBERG_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${ICEBERG_SECRET_ACCESS_KEY}
      AWS_REGION: us-east-1
      CATALOG_WAREHOUSE: s3://warehouse/
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      CATALOG_S3_ENDPOINT: ${MINIO_HOST}:${MINIO_PORT}
    networks:
      - datalakehouse-network

networks:
  datalakehouse-network:
    external: true