services:
#################################################################
# spark-iceberg
#################################################################
  spark-iceberg:
    container_name: spark-iceberg
    image: my-spark-iceberg
    build:
      context: spark
      dockerfile: Dockerfile
    environment:
      CATALOG_TYPE: nessie
      NESSIE_URI: ${NESSIE_URI}
      WAREHOUSE: s3a://warehouse/
      AWS_S3_ENDPOINT: ${MINIO_HOST}:${MINIO_PORT}
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_REGION: us-east-1
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME}
      AZURE_STORAGE_ACCOUNT_ACCESS_KEY: ${AZURE_STORAGE_ACCOUNT_ACCESS_KEY}
    ports:
      - 8888:8888
      - 8081:8080
      - 4040:4040
      - 10000:10000
      - 10001:10001
    volumes:
      - /opt/warehouse:/home/iceberg/warehouse
      - ${SPARK_PROJ_DIR:-.}/notebooks:/home/iceberg/notebooks/notebooks
      - ${SPARK_PROJ_DIR:-.}/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ${SPARK_PROJ_DIR:-.}/data:/opt/spark/data
    entrypoint: ["/bin/bash", "-c"]
    command: ["notebook"]
    networks:
      - datalakehouse-network
      
networks:
  datalakehouse-network:
    external: true