[minio_source]
s3_bucket = "s3a://seed"

[minio_target]
s3_bucket = "s3a://warehouse"

[read_options]
header = true
inferSchema = true
sep = ","

[source]

[source.sales]
source_path = "adventure_works/sales/*.csv"
target_path = "adventure_works/sales.csv"
enabled = true

[source.customer]
source_path = "adventure_works/customer/*.csv"
target_path = "adventure_works/customer.csv"
enabled = true

[source.product]
source_path = "adventure_works/product/*.csv"
target_path = "adventure_works/product.csv"
enabled = true

[source.currency]
source_path = "adventure_works/currency/*.csv"
target_path = "adventure_works/currency.csv"
enabled = true

[source.currency_rate]
source_path = "adventure_works/currency_rate/*.csv"
target_path = "adventure_works/currency_rate.csv"
enabled = true